/**
 * @format
 * @flow strict-local
 */

export const RESET = '@SEARCH_RESULT_VIEW_RESET';

export const REFRESHING = '@SEARCH_RESULT_VIEW_REFRESHING';

export const SEARCHED = '@SEARCH_RESULT_VIEW_SEARCHED';

export const RESULTS = '@SEARCH_RESULT_VIEW_RESULTS';

export const FEEDS_PAGING_LOADING = '@SEARCH_RESULT_VIEW_FEEDS_PAGING_LOADING';
export const FEEDS_PAGING_PAGE = '@SEARCH_RESULT_VIEW_FEEDS_PAGING_PAGE';
export const FEEDS_PAGING_LENGTH = '@SEARCH_RESULT_VIEW_FEEDS_PAGING_LENGTH';

export const FEEDS = '@SEARCH_RESULT_VIEW_FEEDS';
export const FEEDS_UPDATE_FEED = '@SEARCH_RESULT_VIEW_FEEDS_UPDATE_FEED';
