/**
 * @format
 * @flow strict-local
 */

export const RESET = '@SEARCH_RESULT_VIEW_RESET';

export const REFRESHING = '@SEARCH_RESULT_VIEW_REFRESHING';

export const SEARCHED = '@SEARCH_RESULT_VIEW_SEARCHED';

export const RESULTS = '@SEARCH_RESULT_VIEW_RESULTS';

export const SEARCH_RESULT_LIST_PAGING_LOADING = '@SEARCH_RESULT_VIEW_SEARCH_RESULT_LIST_PAGING_LOADING';
export const SEARCH_RESULT_LIST_PAGING_PAGE = '@SEARCH_RESULT_VIEW_SEARCH_RESULT_LIST_PAGING_PAGE';
export const SEARCH_RESULT_LIST_PAGING_LENGTH = '@SEARCH_RESULT_VIEW_SEARCH_RESULT_LIST_PAGING_LENGTH';

export const SEARCH_RESULT_LIST_DATA = '@SEARCH_RESULT_VIEW_SEARCH_RESULT_LIST_DATA';
export const SEARCH_RESULT_LIST_UPDATE_DATA = '@SEARCH_RESULT_VIEW_SEARCH_RESULT_LIST_UPDATE_DATA';
