/**
 * @format
 * @flow strict-local
 */

export const RESET = '@SEARCH_RESULT_RESET';

export const REFRESHING = '@SEARCH_RESULT_REFRESHING';

export const RESULTS = '@SEARCH_RESULT_RESULTS';

export const FEEDS_PAGING_LOADING = '@SEARCH_RESULT_FEEDS_PAGING_LOADING';
export const FEEDS_PAGING_PAGE = '@SEARCH_RESULT_FEEDS_PAGING_PAGE';
export const FEEDS_PAGING_LENGTH = '@SEARCH_RESULT_FEEDS_PAGING_LENGTH';

export const FEEDS = '@SEARCH_RESULT_FEEDS';
export const FEEDS_UPDATE_FEED = '@SEARCH_RESULT_FEEDS_UPDATE_FEED';
