/**
 * @format
 * @flow strict-local
 */

export const RESET = '@PROFILE_CAST_SHEET_EDITION_VIEW_RESET';

export const SET_ACCOUNT_INFO = '@PROFILE_CAST_SHEET_EDITION_VIEW_SET_ACCOUNT_INFO';
export const ADD_ACCOUNT_INFO = '@PROFILE_CAST_SHEET_EDITION_VIEW_ADD_ACCOUNT_INFO';
export const DELETE_ACCOUNT_INFO = '@PROFILE_CAST_SHEET_EDITION_VIEW_DELETE_ACCOUNT_INFO';

export const FOCUSED_TAG = '@PROFILE_CAST_SHEET_EDITION_VIEW_FOCUSED_TAG';
