/**
 * @format
 * @flow strict-local
 */

export const RESET = '@PROFILE_CAST_SHEET_EDITION_VIEW_RESET';

export const ADD_ACCOUNT_INFO = '@PROFILE_CAST_SHEET_EDITION_VIEW_ADD_ACCOUNT_INFO';
export const DELETE_ACCOUNT_INFO = '@PROFILE_CAST_SHEET_EDITION_VIEW_DELETE_ACCOUNT_INFO';
