/**
 * @format
 * @flow strict-local
 */

export const RESET = '@LOGIN_VIEW_RESET';

export const ADD_REF = '@LOGIN_VIEW_ADD_REF';

export const CREDENTIALS_EMAIL = '@LOGIN_VIEW_CREDENTIALS_EMAIL';
export const CREDENTIALS_EMAIL_MESSAGE = '@LOGIN_VIEW_CREDENTIALS_EMAIL_MESSAGE';

export const CREDENTIALS_PASSWORD = '@LOGIN_VIEW_CREDENTIALS_PASSWORD';
export const CREDENTIALS_PASSWORD_MESSAGE =
  '@LOGIN_VIEW_CREDENTIALS_PASSWORD_MESSAGE';

export const SUCCESSLOGIN =
  '@LOGIN_VIEW_SUCCESSLOGIN';