/**
 * @format
 * @flow strict-local
 */

export const RESET = '@LOGIN_RESET';

export const ADD_REF = '@LOGIN_ADD_REF';

export const CREDENTIALS_EMAIL = '@LOGIN_CREDENTIALS_EMAIL';
export const CREDENTIALS_EMAIL_MESSAGE = '@LOGIN_CREDENTIALS_EMAIL_MESSAGE';

export const CREDENTIALS_PASSWORD = '@LOGIN_CREDENTIALS_PASSWORD';
export const CREDENTIALS_PASSWORD_MESSAGE =
  '@LOGIN_CREDENTIALS_PASSWORD_MESSAGE';
