/**
 * @format
 * @flow strict-local
 */

export const RESET = '@ACCOUNT_CHANGE_PASSWORD_STEP_2_VIEW_RESET';

export const ADD_REF = '@ACCOUNT_CHANGE_PASSWORD_STEP_2_VIEW_ADD_REF';

export const ACCOUNT_NEW_PASSWORD = '@ACCOUNT_CHANGE_PASSWORD_STEP_2_VIEW_ACCOUNT_NEW_PASSWORD';
export const ACCOUNT_CONFIRMATION = '@ACCOUNT_CHANGE_PASSWORD_STEP_2_VIEW_ACCOUNT_CONFIRMATION';

export const ACCOUNT_PASSWORD_VALIDATION_LENGTH = '@ACCOUNT_CHANGE_PASSWORD_STEP_2_VIEW_ACCOUNT_PASSWORD_VALIDATION_LENGTH';
export const ACCOUNT_PASSWORD_VALIDATION_SYMBOL = '@ACCOUNT_CHANGE_PASSWORD_STEP_2_VIEW_ACCOUNT_PASSWORD_VALIDATION_SYMBOL';
export const ACCOUNT_PASSWORD_VALIDATION_LOWER_CASE = '@ACCOUNT_CHANGE_PASSWORD_STEP_2_VIEW_ACCOUNT_PASSWORD_VALIDATION_LOWER_CASE';
export const ACCOUNT_PASSWORD_VALIDATION_UPPER_CASE = '@ACCOUNT_CHANGE_PASSWORD_STEP_2_VIEW_ACCOUNT_PASSWORD_VALIDATION_UPPER_CASE';
