/**
 * @format
 * @flow strict-local
 */

export const RESET = '@ACCOUNT_CHANGE_PASSWORD_STEP_2_VIEW_RESET';

export const ADD_REF = '@ACCOUNT_CHANGE_PASSWORD_STEP_2_VIEW_ADD_REF';

export const ACCOUNT_NEW_PASSWORD = '@ACCOUNT_CHANGE_PASSWORD_STEP_2_VIEW_ACCOUNT_NEW_PASSWORD';
export const ACCOUNT_CONFIRMATION = '@ACCOUNT_CHANGE_PASSWORD_STEP_2_VIEW_ACCOUNT_CONFIRMATION';
