/**
 * @format
 * @flow strict-local
 */

export const RESET = '@FEED_VIEW_RESET';

export const REFRESHING = '@FEED_VIEW_REFRESHING';

export const FEEDS_PAGING_LOADING = '@FEED_VIEW_FEEDS_PAGING_LOADING';
export const FEEDS_PAGING_PAGE = '@FEED_VIEW_FEEDS_PAGING_PAGE';
export const FEEDS_PAGING_LENGTH = '@FEED_VIEW_FEEDS_PAGING_LENGTH';

export const FEEDS = '@FEED_VIEW_FEEDS';
export const FEEDS_UPDATE_FEED = '@FEED_VIEW_FEEDS_UPDATE_FEED';
