/**
 * @format
 * @flow strict-local
 */

export const RESET = '@SIGN_UP_VIEW_RESET';

export const ADD_REF = '@SIGN_UP_VIEW_ADD_REF';

// export const ACCOUNT_FIRSTNAME_EN = '@SIGN_UP_VIEW_ACCOUNT_FIRSTNAME_EN';
// export const ACCOUNT_LASTNAME_EN = '@SIGN_UP_VIEW_ACCOUNT_LASTNAME_EN';
// export const ACCOUNT_FIRSTNAME_ZH = '@SIGN_UP_VIEW_ACCOUNT_FIRSTNAME_ZH';
// export const ACCOUNT_LASTNAME_ZH = '@SIGN_UP_VIEW_ACCOUNT_LASTNAME_ZH';
// export const ACCOUNT_NICKNAME = '@SIGN_UP_VIEW_ACCOUNT_NICKNAME';

export const ACCOUNT_EMAIL = '@SIGN_UP_VIEW_ACCOUNT_EMAIL';

export const ACCOUNT_PHONE_CODE = '@SIGN_UP_VIEW_ACCOUNT_PHONE_CODE';
export const ACCOUNT_PHONE_NUMBER = '@SIGN_UP_VIEW_ACCOUNT_PHONE_NUMBER';

export const ACCOUNT_PASSWORD = '@SIGN_UP_VIEW_ACCOUNT_PASSWORD';

export const ACCOUNT_PASSWORD_VALIDATION_LENGTH = '@SIGN_UP_VIEW_ACCOUNT_PASSWORD_VALIDATION_LENGTH';
export const ACCOUNT_PASSWORD_VALIDATION_SYMBOL = '@SIGN_UP_VIEW_ACCOUNT_PASSWORD_VALIDATION_SYMBOL';
export const ACCOUNT_PASSWORD_VALIDATION_LOWER_CASE = '@SIGN_UP_VIEW_ACCOUNT_PASSWORD_VALIDATION_LOWER_CASE';
export const ACCOUNT_PASSWORD_VALIDATION_UPPER_CASE = '@SIGN_UP_VIEW_ACCOUNT_PASSWORD_VALIDATION_UPPER_CASE';
