/**
 * @format
 * @flow strict-local
 */

export const RESET = '@SIGN_UP_RESET';

export const ACCOUNT_FIRSTNAME_EN = '@SIGN_UP_ACCOUNT_FIRSTNAME_EN';
export const ACCOUNT_LASTNAME_EN = '@SIGN_UP_ACCOUNT_LASTNAME_EN';
export const ACCOUNT_FIRSTNAME_ZH = '@SIGN_UP_ACCOUNT_FIRSTNAME_ZH';
export const ACCOUNT_LASTNAME_ZH = '@SIGN_UP_ACCOUNT_LASTNAME_ZH';
export const ACCOUNT_NICKNAME = '@SIGN_UP_ACCOUNT_NICKNAME';

export const ACCOUNT_EMAIL = '@SIGN_UP_ACCOUNT_EMAIL';

export const ACCOUNT_PHONE_CODE = '@SIGN_UP_ACCOUNT_PHONE_CODE';
export const ACCOUNT_PHONE_NUMBER = '@SIGN_UP_ACCOUNT_PHONE_NUMBER';

export const ACCOUNT_PASSWORD = '@SIGN_UP_ACCOUNT_PASSWORD';
