/**
 * @format
 * @flow strict-local
 */

export const CREDENTIALS_ID = '@LOGIN_CREDENTIALS_ID';
export const CREDENTIALS_ID_MESSAGE = '@LOGIN_CREDENTIALS_ID_MESSAGE';

export const CREDENTIALS_PASSWORD = '@LOGIN_CREDENTIALS_PASSWORD';
export const CREDENTIALS_PASSWORD_MESSAGE =
  '@LOGIN_CREDENTIALS_PASSWORD_MESSAGE';
