/**
 * @format
 * @flow strict-local
 */

export const RESET = '@SIGN_UP_RESET';

export const ACCOUNT_NAME = '@SIGN_UP_ACCOUNT_NAME';
export const ACCOUNT_NAME_MESSAGE = '@SIGN_UP_ACCOUNT_NAME_MESSAGE';

export const ACCOUNT_EMAIL = '@SIGN_UP_ACCOUNT_EMAIL';
export const ACCOUNT_EMAIL_MESSAGE = '@SIGN_UP_ACCOUNT_EMAIL_MESSAGE';

export const ACCOUNT_PHONE_CODE = '@SIGN_UP_ACCOUNT_PHONE_CODE';
export const ACCOUNT_PHONE_NUMBER = '@SIGN_UP_ACCOUNT_PHONE_NUMBER';
export const ACCOUNT_PHONE_MESSAGE = '@SIGN_UP_ACCOUNT_PHONE_MESSAGE';

export const ACCOUNT_PASSWORD = '@SIGN_UP_ACCOUNT_PASSWORD';
export const ACCOUNT_PASSWORD_MESSAGE = '@SIGN_UP_ACCOUNT_PASSWORD_MESSAGE';
