/**
 * @format
 * @flow strict-local
 */

export const RESET = '@FIND_TALENT_SECTION_RESET';

export const TAGS = '@FIND_TALENT_SECTION_TAGS';
export const TAGS_UPDATE_GROUP_FRAME = '@FIND_TALENT_SECTION_TAGS_UPDATE_GROUP_FRAME';
export const TAGS_UPDATE_TAG = '@FIND_TALENT_SECTION_TAGS_UPDATE_TAG';
