/**
 * @format
 * @flow strict-local
 */

export const RESET = '@PROFILE_INFO_SETUP_SECTION_RESET';

export const NUMBER_OF_INDICATORS = '@PROFILE_INFO_SETUP_SECTION_NUMBER_OF_INDICATORS';
export const PHOTO = '@PROFILE_INFO_SETUP_SECTION_PHOTO';

export const ACCOUNT_FIRSTNAME_EN = '@PROFILE_INFO_SETUP_SECTION_ACCOUNT_FIRSTNAME_EN';
export const ACCOUNT_LASTNAME_EN = '@PROFILE_INFO_SETUP_SECTION_ACCOUNT_LASTNAME_EN';
export const ACCOUNT_FIRSTNAME_ZH = '@PROFILE_INFO_SETUP_SECTION_ACCOUNT_FIRSTNAME_ZH';
export const ACCOUNT_LASTNAME_ZH = '@PROFILE_INFO_SETUP_SECTION_ACCOUNT_LASTNAME_ZH';
export const ACCOUNT_NICKNAME = '@PROFILE_INFO_SETUP_SECTION_ACCOUNT_NICKNAME';
export const ACCOUNT_DISPLAY_FORMAT = '@PROFILE_INFO_SETUP_SECTION_ACCOUNT_DISPLAY_FORMAT';
