/**
 * @format
 * @flow strict-local
 */

export const RESET = '@SETTINGS_STACK_NAVIGATOR_RESET';

export const HIDDEN_RIGHT = '@SETTINGS_STACK_NAVIGATOR_HIDDEN_RIGHT';

export const ENABLED_RIGHT = '@SETTINGS_STACK_NAVIGATOR_ENABLED_RIGHT';

export const ADD_ON_SCREEN_APPEAR = '@SETTINGS_STACK_NAVIGATOR_ADD_ON_SCREEN_APPEAR';

export const ADD_ON_RIGHT_BUTTON_PRESS = '@SETTINGS_STACK_NAVIGATOR_ADD_ON_RIGHT_BUTTON_PRESS';
