/**
 * @format
 * @flow strict-local
 */

export const RESET = '@SIGN_UP_STACK_NAVIGATOR_RESET';

export const HIDDEN_RIGHT = '@SIGN_UP_STACK_NAVIGATOR_HIDDEN_RIGHT';

export const ON_RIGHT_BUTTON_PRESS = '@SIGN_UP_STACK_NAVIGATOR_ON_RIGHT_BUTTON_PRESS';
