/**
 * @format
 * @flow strict-local
 */

export const RESET = '@CREATE_PROJECT_STEP_2_RESET';

export const ADD_AVAILABILITY = '@CREATE_PROJECT_STEP_2_ADD_AVAILABILITY';
export const UPDATE_AVAILABILITY = '@CREATE_PROJECT_STEP_2_UPDATE_AVAILABILITY';
export const DELETE_AVAILABILITY = '@CREATE_PROJECT_STEP_2_DELETE_AVAILABILITY';
