/**
 * @format
 * @flow strict-local
 */

export const RESET = '@CREATE_PROJECT_STEP_2_VIEW_RESET';

export const ADD_AVAILABILITY = '@CREATE_PROJECT_STEP_2_VIEW_ADD_AVAILABILITY';
export const UPDATE_AVAILABILITY = '@CREATE_PROJECT_STEP_2_VIEW_UPDATE_AVAILABILITY';
export const DELETE_AVAILABILITY = '@CREATE_PROJECT_STEP_2_VIEW_DELETE_AVAILABILITY';
